//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constructability_Review_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CRCTestEntities1 : DbContext
    {
        public CRCTestEntities1()
            : base("name=CRCTestEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblChecklistReview> tblChecklistReviews { get; set; }
        public virtual DbSet<tblChecklistReviewItem> tblChecklistReviewItems { get; set; }
        public virtual DbSet<tblChecklistReviewItemComment> tblChecklistReviewItemComments { get; set; }
        public virtual DbSet<tblJob> tblJobs { get; set; }
        public virtual DbSet<tblTemplateDesignLevel> tblTemplateDesignLevels { get; set; }
        public virtual DbSet<tblTemplateDivision> tblTemplateDivisions { get; set; }
        public virtual DbSet<tblTemplateMajorSection> tblTemplateMajorSections { get; set; }
        public virtual DbSet<tblTemplateResult> tblTemplateResults { get; set; }
        public virtual DbSet<tblTemplateReviewerType> tblTemplateReviewerTypes { get; set; }
        public virtual DbSet<tblTemplateSection> tblTemplateSections { get; set; }
        public virtual DbSet<tblTemplateSectionItem> tblTemplateSectionItems { get; set; }
    
        public virtual int spBuild_JobOppList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spBuild_JobOppList");
        }
    
        public virtual ObjectResult<Nullable<int>> spBuild_NewChecklistReviewForEdit(string job, string user)
        {
            var jobParameter = job != null ?
                new ObjectParameter("Job", job) :
                new ObjectParameter("Job", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spBuild_NewChecklistReviewForEdit", jobParameter, userParameter);
        }
    }
}
