//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constructability_Review_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChecklistReviewItemComment
    {
        public int ChecklistReviewItemCommentID { get; set; }
        public Nullable<int> ChecklistReviewItemID { get; set; }
        public Nullable<int> ChecklistReviewDesignLevelID { get; set; }
        public string ChecklistReviewDesignLevelCode { get; set; }
        public string ChecklistReviewDesignLevelName { get; set; }
        public string ChecklistReviewItemReviewerRole { get; set; }
        public string ChecklistReviewItemReviewerResultName { get; set; }
        public string ChecklistReviewItemReviewerResultComments { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public string Attachment { get; set; }
        public string AttachmentName { get; set; }
    
        public virtual tblChecklistReviewItem tblChecklistReviewItem { get; set; }
    }
}
