//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constructability_Review_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChecklistReviewItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblChecklistReviewItem()
        {
            this.tblChecklistReviewItemComments = new HashSet<tblChecklistReviewItemComment>();
        }
    
        public int ChecklistReviewItemID { get; set; }
        public Nullable<int> ChecklistReviewID { get; set; }
        public Nullable<int> ChecklistReviewItemMajorSectionID { get; set; }
        public string ChecklistReviewItemMajorSectionName { get; set; }
        public Nullable<int> ChecklistReviewItemMajorSectionSortOrder { get; set; }
        public Nullable<int> ChecklistReviewItemDivisionID { get; set; }
        public string ChecklistReviewItemDivisionNumber { get; set; }
        public string ChecklistReviewItemDivisionName { get; set; }
        public string ChecklistReviewItemDivisionPublic { get; set; }
        public Nullable<int> ChecklistReviewItemDivisionSortOrder { get; set; }
        public Nullable<int> ChecklistReviewItemSectionID { get; set; }
        public string ChecklistReviewItemSectionName { get; set; }
        public Nullable<int> ChecklistReviewItemSectionSortOrder { get; set; }
        public Nullable<int> ChecklistReviewItemSectionItemID { get; set; }
        public string ChecklistReviewItemSectionItemCode { get; set; }
        public string ChecklistReviewItemSectionItemName { get; set; }
        public string ChecklistReviewItemSectionItemLink { get; set; }
        public Nullable<int> ChecklistReviewItemSectionItemSortOrder { get; set; }
        public bool ChecklistReviewItemReviewerActive { get; set; }
        public bool ChecklistReviewItemVisible { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
    
        public virtual tblChecklistReview tblChecklistReview { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChecklistReviewItemComment> tblChecklistReviewItemComments { get; set; }
    }
}
