//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constructability_Review_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblJob()
        {
            this.tblChecklistReviews = new HashSet<tblChecklistReview>();
        }
    
        public byte JCCo { get; set; }
        public string Job { get; set; }
        public Nullable<int> JobNum { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChecklistReview> tblChecklistReviews { get; set; }
    }
}
