//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constructability_Review_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemplateDivision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTemplateDivision()
        {
            this.tblTemplateSections = new HashSet<tblTemplateSection>();
        }
    
        public int TemplateDivisionID { get; set; }
        public string TemplateDivisionNumber { get; set; }
        public string TemplateDivisionName { get; set; }
        public string TemplateDivisionPublic { get; set; }
        public int TemplateMajorSectionID { get; set; }
        public int TemplateDivisionSortOrder { get; set; }
        public bool TemplateDivisionActive { get; set; }
    
        public virtual tblTemplateMajorSection tblTemplateMajorSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTemplateSection> tblTemplateSections { get; set; }
    }
}
