//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constructability_Review_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemplateDesignLevel
    {
        public int TemplateDesignLevelID { get; set; }
        public string TemplateDesignLevelCode { get; set; }
        public string TemplateDesignLevelName { get; set; }
        public int TemplateDesignLevelSortOrder { get; set; }
        public bool TemplateDesignLevelActive { get; set; }
    }
}
