//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constructability_Review_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemplateMajorSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTemplateMajorSection()
        {
            this.tblTemplateDivisions = new HashSet<tblTemplateDivision>();
            this.tblTemplateSections = new HashSet<tblTemplateSection>();
        }
    
        public int TemplateMajorSectionID { get; set; }
        public string TemplateMajorSectionName { get; set; }
        public int TemplateMajorSectionSortOrder { get; set; }
        public bool TemplateMajorSectionActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTemplateDivision> tblTemplateDivisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTemplateSection> tblTemplateSections { get; set; }
    }
}
