//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constructability_Review_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemplateReviewerType
    {
        public int TemplateReviewerTypeID { get; set; }
        public string TemplateReviewerTypeCode { get; set; }
        public string TemplateReviewerTypeName { get; set; }
        public int TemplateReviewerTypeSortOrder { get; set; }
        public bool TemplateReviewerTypeActive { get; set; }
    }
}
