//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constructability_Review_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemplateResult
    {
        public int TemplateResultID { get; set; }
        public string TemplateResultName { get; set; }
        public int TemplateResultSortOrder { get; set; }
        public bool TemplateResultActive { get; set; }
    }
}
